//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERFC.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_attachments
    {
        public int attachmentId { get; set; }
        public int transactionId { get; set; }
        public string attachtype { get; set; }
        public string filename { get; set; }
        public string newfilename { get; set; }
        public string filetype { get; set; }
        public string uploadtype { get; set; }
        public string created_by { get; set; }
        public System.DateTime create_date { get; set; }
    }
}
