//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERFC.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_appedi
    {
        public int ediId { get; set; }
        public string caption { get; set; }
        public string description { get; set; }
        public string source { get; set; }
        public string destination { get; set; }
        public string extension { get; set; }
    }
}
