//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERFC.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_branchmst
    {
        public string brancode { get; set; }
        public string branname { get; set; }
        public string address { get; set; }
        public string status { get; set; }
        public string districtcode { get; set; }
        public string branchheadname { get; set; }
        public string branchheadcontact { get; set; }
        public string branalias { get; set; }
        public string mapreference { get; set; }
        public string branchheadid { get; set; }
        public string branchheademail { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string sbu { get; set; }
        public byte withpism { get; set; }
        public bool withwfmsdb { get; set; }
        public Nullable<int> wfmsdbId { get; set; }
        public byte reportflag { get; set; }
        public string hrisbranchcode { get; set; }
        public string created_by { get; set; }
        public System.DateTime create_date { get; set; }
    }
}
