//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERFC.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_appbroadcastmsg
    {
        public int msgId { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public string creaby { get; set; }
        public Nullable<System.DateTime> creadte { get; set; }
        public Nullable<int> daylive { get; set; }
        public Nullable<bool> isshow { get; set; }
        public Nullable<int> msgtype { get; set; }
    }
}
