//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERFC.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_appmenuuser
    {
        public int menuId { get; set; }
        public int userId { get; set; }
        public Nullable<bool> canadd { get; set; }
        public Nullable<bool> canedit { get; set; }
        public Nullable<bool> candelete { get; set; }
        public Nullable<bool> canview { get; set; }
        public Nullable<bool> canopen { get; set; }
    
        public virtual core_users core_users { get; set; }
    }
}
