//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERFC.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_appnotification
    {
        public int notifyId { get; set; }
        public string appcode { get; set; }
        public Nullable<int> sender { get; set; }
        public Nullable<int> recipient { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public bool isread { get; set; }
        public System.DateTime createdate { get; set; }
    }
}
