//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERFC.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_vAdminMenu
    {
        public int parentId { get; set; }
        public string parentName { get; set; }
        public Nullable<int> parentmenuorder { get; set; }
        public string parenticon { get; set; }
        public Nullable<int> userId { get; set; }
        public int sysId { get; set; }
        public string menucode { get; set; }
    }
}
