//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERFC.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_appsystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public core_appsystem()
        {
            this.core_appmenu = new HashSet<core_appmenu>();
            this.core_userswarehouse = new HashSet<core_userswarehouse>();
        }
    
        public int sysId { get; set; }
        public string syscode { get; set; }
        public string sysname { get; set; }
        public string sysdescription { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string about { get; set; }
        public Nullable<bool> showwebapps { get; set; }
        public Nullable<bool> showusermenu { get; set; }
        public Nullable<bool> ismaintenance { get; set; }
        public string emailsupport { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<core_appmenu> core_appmenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<core_userswarehouse> core_userswarehouse { get; set; }
    }
}
