//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERFC.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_appsettings
    {
        public int id { get; set; }
        public int appID { get; set; }
        public string SittingName { get; set; }
        public string SettingDescription { get; set; }
        public string SettingValue { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
