//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERFC.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_appversion
    {
        public int versionId { get; set; }
        public Nullable<int> systemId { get; set; }
        public string verno { get; set; }
        public string verreleasenote { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
