//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERFC.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERFCDBEntities : DbContext
    {
        public ERFCDBEntities()
            : base("name=ERFCDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<core_appbroadcastmsg> core_appbroadcastmsg { get; set; }
        public virtual DbSet<core_appedi> core_appedi { get; set; }
        public virtual DbSet<core_appmenu> core_appmenu { get; set; }
        public virtual DbSet<core_appmenuuser> core_appmenuuser { get; set; }
        public virtual DbSet<core_appnotification> core_appnotification { get; set; }
        public virtual DbSet<core_appsettings> core_appsettings { get; set; }
        public virtual DbSet<core_appsystem> core_appsystem { get; set; }
        public virtual DbSet<core_appsystemuser> core_appsystemuser { get; set; }
        public virtual DbSet<core_appversion> core_appversion { get; set; }
        public virtual DbSet<core_attachments> core_attachments { get; set; }
        public virtual DbSet<core_branchmst> core_branchmst { get; set; }
        public virtual DbSet<core_users> core_users { get; set; }
        public virtual DbSet<core_userswarehouse> core_userswarehouse { get; set; }
        public virtual DbSet<core_audit_trail> core_audit_trail { get; set; }
        public virtual DbSet<core_vAdminMenu> core_vAdminMenu { get; set; }
        public virtual DbSet<core_vParentMenu> core_vParentMenu { get; set; }
    }
}
